### ISSUE TITLE
Link to LLOOGG in FAQ redirects to phishing/scam site

### ISSUE THREAD

**Issue by velut** [redis/redis-io#180]
Hi,

In the page at https://redis.io/topics/faq, the link to LLOOGG redirects to a phishing/scam site.

> Why did you start the Redis project?
> 
> Originally Redis was started in order to scale LLOOGG. But after I got the basic server working I liked the idea to share the work with other people, and Redis was turned into an open source project.

**Comment by odyseeus** [comment]
Looks like the actual website now, I think we can close the issue.

**Comment by itamarhaber** [comment]
Actually, it isn't the original site - imo the link should be removed.

**Comment by odyseeus** [comment]
http://demo.lloogg.com/ seems to be listed on the official repo, but this subdomain is nowhere to be found... I am guessing someone just bought lloogg.com after it expired and put in some random content. 

I think we can just redirect it to https://github.com/antirez/lloogg if necessary
