### ISSUE TITLE
Redis Clients page C# link goes to wrong section

### ISSUE THREAD

**Issue by Assisting** [redis/redis-io#182]
Repro:

1. Go [here](https://redis.io/clients)
2. Click "C#"
3. Browser directs user toward C section

I'll submit a PR with a fix shortly. 😉

**Comment by itamarhaber** [comment]
Looks relate to #134 and https://github.com/antirez/redis-doc/pull/1087. Definitely needs resolution.

**Comment by Assisting** [comment]
Oh, whoops, I didn't look hard enough for other PRs. Mine has the advantage of not changing the text being displayed but honestly either one would be perfectly clear.

**Comment by itamarhaber** [comment]
@Assisting I agree, yours deals with the root cause and the other just with the symptom.

**Comment by itamarhaber** [comment]
Closed via #220
