### ISSUE TITLE
try.redis.io should not be advertised 

### ISSUE THREAD

**Issue by lyrixx** [redis/redis-io#189]
I discoverd http://try.redis.io/ has been shut down.
On this page, there is a link to redis.io 
But on redis.io there is a link to http://try.redis.io/. 
This is an infinite loop :D 

>Try it
Ready for a test drive? Check this interactive tutorial that will walk you through the most important features of Redis.

**Comment by itamarhaber** [comment]
Thanks @lyrixx - #188 should provide a form of resolution.

**Comment by ayruslore** [comment]
Yes it does. I think this can be closed too

**Comment by itamarhaber** [comment]
Thanks for bumping this - closing.
