### ISSUE TITLE
Bring try.redis.io back!

### ISSUE THREAD

**Issue by pensierinmusica** [redis/redis-io#191]
May I ask why try.redis.io has been shut down?

It was an awesome project, and we were using it a lot in our school to introduce Redis to students.

It was by far the best introductory tutorial I've seen about Redis.

Any chance to see it working again? Our students would be happy to volunteer if help is needed.

Thx, cheers!

**Comment by pensierinmusica** [comment]
@antirez, @pietern, @alexmchale, @badboy

**Comment by antirez** [comment]
Ok, I'll take care.

**Comment by pensierinmusica** [comment]
😀yey @antirez thanks!!

**Comment by badboy** [comment]
I sent out an email earlier this year to antirez (and the mailing list, but I think it bounced or doesn't exist anymore):

> In late 2012/early 2013 [1][2] I took over maintenance of try.redis and ran it on one of my servers ever since.
> I marked the repository as unmaintained in March 2018.

> After a security problem with the current code I shut down the hosted instance a while ago.
> Now that I also moved servers, try.redis.io is officially dead.

> Its code is still available: https://github.com/badboy/try.redis

> @antirez: Please remove the DNS entries for try.redis.io.

**Comment by badboy** [comment]
@antirez or whoever runs try.redis.io now: could you please change the sentence in the footer about who’s running and maintaining it? Thanks.

**Comment by ayruslore** [comment]
The website is available again - https://try.redis.io/. This issue can be closed.

**Comment by B0wi3** [comment]
Shut down once more...
