### ISSUE TITLE
Outdated Redis PHP Clients

### ISSUE THREAD

**Issue by umairkhan-dev** [redis/redis-io#203]
Some of the PHP clients mentioned [here](https://redis.io/clients#php) are too old / outdated / archived. For example.

1- [swoole/redis-async](https://github.com/swoole/redis-async) - Archived.
2- [jdp/redisent](https://github.com/jdp/redisent) - Last commited in 2013.
3- [shumkov/rediska](https://github.com/Shumkov/Rediska) - No longer maintained.
4- [yampee/Redis](https://github.com/yampee/Redis) - Last commited in 2014.

Kindly update the list.

**Comment by itamarhaber** [comment]
Hello @umairkhan-dev 

Thanks for the heads up - please feel free to submit a PR to the 'clients.json' file in this repository with updates to the `active` property of the relevant clients.

**Comment by umairkhan-dev** [comment]
Hi @itamarhaber 
Please point me to `clients.json` in this repository. Somehow, I can't seem to find it.

Thanks.

**Comment by itamarhaber** [comment]
Sure thing: https://github.com/redis/redis-doc/blob/master/clients.json

**Comment by umairkhan-dev** [comment]
@itamarhaber. Thanks for pointing me to `clients.json`. Its still a mystery to me why I could not find the file myself.

However. I have edited / committed the file. Submitted the PR.

PS. I am new to github environment, so please forgive my mistakes if any.
