### ISSUE TITLE
Redis News / Buzz not updating

### ISSUE THREAD

**Issue by sehrope** [redis/redis-io#206]
The "Redis News" section and "Buzz" pages are not updating. The data being returned from the AJAX source (https://redis-buzz.herokuapp.com/?callback=x) has Oct 2019 as the most recent update. This is kind of weird as on the main home page you see things like "Redis 5 RC5 and Redis 4.0.11 are out!" as recent news items.

Any idea where the code is for that Heroku app or who maintains it? I did not see a repo for it anywhere.

**Comment by itamarhaber** [comment]
Hello @sehrope 

Thanks for reporting this. Regrettably, this is a known issue and we're looking into how it can be resolved.

**Comment by itamarhaber** [comment]
Closed as resolved,
