### ISSUE TITLE
Client side caching concept page has a minor bug

### ISSUE THREAD

**Issue by MichalCho** [redis/redis-io#212]
Hi,
I was reading 
https://redis.io/topics/client-side-caching

and I think there is a bug in the description of the strategy used for client caching.

Moreover in many clients implementations, this is what you want, because a good solution could be to just cache everything that is not already cached, **using a first-in last-out approach**: we may want to cache a fixed number of objects, every new data we retrieve, we could cache it, **discarding the oldest cached object.** 

I think that discarding the oldest element is first-in first-out approach. 
I would crate a PR with the fix but unfortunately I don't know where to find the source.

Br
Michal

**Comment by itamarhaber** [comment]
Hello @MichalCho 

I'm afraid I don't quite follow the issue, but as you're willing to make a PR please do so at https://github.com/redis/redis-doc/blob/master/topics/client-side-caching.md

Closing this in favor of the upcoming PR.

**Comment by MichalCho** [comment]
Thnaks @itamarhaber ,

now I've realized that without a proper formatting my previous message looks quite messy and can be confusing. 
I will craft a PR.

Thanks for the help
