### ISSUE TITLE
ZMSCORE command is not supported

### ISSUE THREAD

**Issue by hollyshi** [redis/redis-io#222]
![image](https://user-images.githubusercontent.com/3378159/100850686-217a6780-34bf-11eb-9ce3-2cede9336330.png)
It looks like ZMSCORE is not supported by the Redis server behind.
https://redis.io/commands/zmscore

**Comment by itamarhaber** [comment]
Hi @hollyshi 

Thanks for the heads up - this is a known issue as the website is running the latest stable version of Redis (6.0.9) to power the examples, and this command will only be introduced in the upcoming 6.2 version. Once that version is officially released this page will work correctly :)

**Comment by hollyshi** [comment]
@itamarhaber  Thanks for the reply.
I wonder if  it is better to explicitly show the latest stable version on the page somewhere. So that nobody will get confused like me. 😃

**Comment by itamarhaber** [comment]
Ok, avoiding confusion makes sense :) I'll try to come up with a scheme to make future commands more visible, but if you have ideas please feel free to suggest.

Closing this for now but feel free to reopen.
