### ISSUE TITLE
Move IRC channel off Freenode

### ISSUE THREAD

**Issue by minus7** [redis/redis-io#239]
After the hostile takeover of Freenode, it'd be best to take a stand by moving off of Freenode like many other projects already did.

Moving to libera.chat would be the most obvious choice.

**Comment by minus7** [comment]
Sad to see you only keep a closed platform, but fair enough.

The IRC channel is still recognized as official by the network. Only antirez has ownership of the channel, but I have ops and can redirect users (and preferrably the lock the channel).

**Comment by itamarhaber** [comment]
Dear @minus7 - I wasn't aware that the room was active and didn't know who had ops/admin there. After the news hit yesterday we considered the removal and it seemed the right thing to do (remove freenode). This wasn't intended to make you sad.

I think that locking the room would be good and would appreciate it if you can make it happen. Redirection is also a possibility, even if only to the redis.io/community page.

The bigger question is whether IRC is still relevant for the project. Personally (and afaik most of the core devs) I haven't spent too much time on freenode, so I can't really attest to its need (official recognition aside). We can definitely reopen on libera or similar, but I guess what I'm wondering is whether anyone would use it. Can you share your experience from #redis on freenode and its usefulness?

**Comment by minus7** [comment]
>I think that locking the room would be good and would appreciate it if you can make it happen. Redirection is also a possibility, even if only to the redis.io/community page.

I already set the topic to redirect users to that page and will lock the channel in the coming days.

>The bigger question is whether IRC is still relevant for the project. Personally (and afaik most of the core devs) I haven't spent too much time on freenode, so I can't really attest to its need (official recognition aside). We can definitely reopen on libera or similar, but I guess what I'm wondering is whether anyone would use it. Can you share your experience from #redis on freenode and its usefulness?

There's usually a handful of user questions per week, so definitely not completely dead.
When I have a question regarding some open source project (that's beyond a quick web search), the first thing I usually try to do is join the channel with the project's name on Freenode; I assume it's the same for lots of the users that join there, too. No idea if that'd carry over to a new network.

Having an official channel (on e.g. libera) would be great, but it'd probably work fine as inofficial channel as well.

**Comment by minus7** [comment]
Update: Freenode staff has seized the channel (along with [700 others](https://mastodon.sdf.org/@kline/106299403921451814)) due to some new rules they made up[1]. Looks like they still let you re-register the channel if you officially represent the project in question, which other channels used to forcibly evict all users.

[1]: See "channel ownership [now](https://web.archive.org/web/20210526014416/https://freenode.net/policies) and [before](https://web.archive.org/web/20210210003016/https://freenode.net/policies).
